source "https://rubygems.org"

gem "rails", "~> 7.0"
gem "sqlite3"
gem "puma"

# TODO [2025-01-01]: Update to latest version
gem "bootsnap", ">= 1.4.4", require: false

group :development, :test do
  # FIXME [2024-12-31]: This gem is deprecated
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem "listen", "~> 3.3"
  # TODO: Add spring for faster development
  gem "spring"
end